authorName: PeterouZh
experimentName: Unified_GAN_cifar100
trialConcurrency: 1
maxExecDuration: 480h
maxTrialNum: 10000
#choice: local, remote, pai
trainingServicePlatform: remote
#searchSpacePath: train_unified_GAN.json
searchSpacePath: train_unified_GAN_v1.json

#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
    parallel_optimize: True
    constant_liar_type: min
trial:
  command:
  codeDir: .
  gpuNum: 1
#machineList can be empty if the platform is local
machineList:
  - ip: "192.168.101.33"
    username: "user321"
    sshKeyPath: "~/.ssh/id_rsa"
    gpuIndices: 0,1,2,3
    useActiveGpu: true
##    preCommand: "source ~/anaconda3/bin/activate py36"
# ssh -o ServerAliveInterval=30 -R 8201:localhost:8201 user321@192.168.101.33

#  - ip: "localhost"
#    username: "it_stu39"
#    passwd: "glassroom"
#    port: 2222
#    gpuIndices: 0,1,2,3
#    useActiveGpu: true
# ssh -o ServerAliveInterval=30 -L 2222:localhost:22  -p 22 it_stu39@node11 -o ProxyCommand='ssh -p 22 it_stu39@202.121.181.113 -W %h:%p'

# ssh -o ServerAliveInterval=30 -R 8101:localhost:8101  -p 22 it_stu39@node11 -o ProxyCommand='ssh -p 22 it_stu39@202.121.181.113 -W %h:%p'

  - ip: "192.168.4.234"
    username: "zhoupeng"
    sshKeyPath: "~/.ssh/id_rsa"
    port: 300
    gpuIndices: 1,2,3
    useActiveGpu: true
# ssh -p 300 -o ServerAliveInterval=30 -R 8201:localhost:8201 zhoupeng@192.168.4.234



#nniManagerIp: 192.168.4.16
#nniManagerIp: 127.0.0.1
nniManagerIp: localhost





