train_BigGAN_c10:
  args:
    shuffle: true
    batch_size: 32
    dataset: C10
    use_data_root: true
    data_root: "datasets/cifar10"
    num_workers: 0
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_epochs: 500
    num_D_steps: 4
    G_ch: 64
    D_ch: 64
    G_lr: 2.e-4
    D_lr: 2.e-4
    G_ortho: 0.0
    G_attn: '0'
    D_attn: '0'
    G_init: N02
    D_init: N02
    ema: true
    use_ema: true
    ema_start: 1000
    test_every: -1
    save_every: 2000
    num_best_copies: 1
    num_save_copies: 1
    seed: 0
  test_every_images: 500000
#  test_every_images: 500
  val_dataloader:
    dataset_kwargs:
      train: false
    use_training_sampler: true
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: "datasets/fid_stats_tf_cifar10_train_32.npz"
    tf_inception_model_dir: "datasets/tf_inception_model"
    num_inception_images: 50000
#    num_inception_images: 500


train_BigGAN_c100:
  base: train_BigGAN_c10
  args:
    dataset: C100
    data_root: "datasets/cifar100"
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: "datasets/fid_stats_tf_cifar100_train_32.npz"
    tf_inception_model_dir: "datasets/tf_inception_model"
#    num_inception_images: 500
    num_inception_images: 50000







