train_50k_vit_disc_unified_GAN:
  args:
    shuffle: true
    batch_size: 32
    dataset: C100
    use_data_root: true
    data_root: datasets/cifar100
    num_workers: 0
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_epochs: 50000000
    num_D_steps: 4
    G_ch: 64
    D_ch: 64
    G_lr: 0.0002
    D_lr: 0.0002
    G_ortho: 0.0
    G_attn: '0'
    D_attn: '0'
    G_init: N02
    D_init: N02
    ema: true
    use_ema: true
    ema_start: 5000
    test_every: 5000000
    save_every: 2000
    num_best_copies: 1
    num_save_copies: 1
    seed: 0
    model: exp.vit_net.BigGAN_unified_loss
    G_eval_mode: true
    which_train_fn: exp.unified_loss.train_fns
  train_dataloader:
    dataset_kwargs:
      train: true
  val_dataloader:
    dataset_kwargs:
      train: false
    use_training_sampler: true
  test_every_images: 500000
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: datasets/tf_fid_stat/fid_stats_tf_cifar100_train_32.npz
    tf_inception_model_dir: datasets/tf_inception_model
    num_inception_images: 50000
  Discriminator:
#    weight_decay: 0.0005
    weight_decay: 0.001
    patch_size: 4
    dim: 256
    depth: 3
    heads: 8
    mlp_dim: 512
  unified_loss:
    gamma: 1.0
    margin: 0.0
    default_label: 0

debug_train_50k_vit_disc_unified_GAN:
  base:
    - train_50k_vit_disc_unified_GAN
  GAN_metric:
    num_inception_images: 5000
  train_dataloader:
    dataset_kwargs:
      val_split: 0.04
      train: validate
  test_every_images: 20000