train_full_conv_disc:
  args:
    shuffle: true
    batch_size: 32
    dataset: C100
    use_data_root: true
    data_root: datasets/cifar100
    num_workers: 0
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_epochs: 50000000
    num_D_steps: 4
    G_ch: 64
    D_ch: 64
    G_lr: 0.0002
    D_lr: 0.0002
    G_ortho: 0.0
    G_attn: '0'
    D_attn: '0'
    G_init: N02
    D_init: N02
    ema: true
    use_ema: true
    ema_start: 5000
    test_every: 5000000
    save_every: 2000
    num_best_copies: 1
    num_save_copies: 1
    seed: 0
    model: "exp.cmconv.net_cmconv_full_conv_discriminator"
    G_eval_mode: true
    which_train_fn: train_fns
  train_dataloader:
    dataset_kwargs:
      train: true
  val_dataloader:
    dataset_kwargs:
      train: false
    use_training_sampler: true
  test_every_images: 500000
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: datasets/tf_fid_stat/fid_stats_tf_cifar100_train_32.npz
    tf_inception_model_dir: datasets/tf_inception_model
    num_inception_images: 50000
  discriminator:
    cmconv_out_channel: 1
    CMConv_cfg:
      name: "EmbeddingModulatedConv2d"
      n_classes: 100
      zero_embedding: false
      spectral_norm: true
      ModulatedConv2d_cfg:
        name: "ModulatedConv2d"
        kernel_size: 3
        use_affine: false
#        use_affine: true
        demodulate: true
#        demodulate: false
        init: "ortho"
        style_plus_one: true


debug_train_full_conv_disc:
  base:
    - train_full_conv_disc
  GAN_metric:
    num_inception_images: 5000
  train_dataloader:
    dataset_kwargs:
      val_split: 0.04
      train: validate
  test_every_images: 20000