train_cifar10_CBN_position:
  args:
    shuffle: true
    batch_size: 32
    dataset: C10
    use_data_root: true
    data_root: "datasets/cifar10"
    num_workers: 0
    parallel: false
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_epochs: 340
    num_D_steps: 5
    G_ch: 64
    D_ch: 32
    G_lr: 2.e-4
    D_lr: 2.e-4
    G_ortho: 0.0
    G_attn: '0'
    D_attn: '0'
    G_init: N02
    D_init: N02
    ema: true
    use_ema: true
    ema_start: 1000
    test_every: 5000
    save_every: 2000
    num_best_copies: 5
    num_save_copies: 2
    seed: 0
    model: "method.BigGAN_v1"
#    G_param: "SN"
    G_param: ""
  generator:
    cbn_index:
      - 0
      - 1
      - 2
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: "datasets/tf_fid_stat/\
      fid_stats_tf_cifar10_train_32.npz"
    tf_inception_model_dir: "datasets/tf_inception_model"
#    num_inception_images: 500
    num_inception_images: 50000


save_FID_CBN_location_figure:
  args:
    num_gpus: 1
  start:
    name: "save_FID_CBN_location_figure"
  properties:
    xlim:
      - 0
      - 336
    ylim:
      - 0
      - 40
  fid_files:
    BigGAN_CBN_in_all_blocks:
      log_file:
        "results/CIFAR10/train_cifar10_20200410-13_41_09_498/textlog/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in all blocks"
        marker: "."
    BigGAN_CBN_in_blocks_0:
      log_file:
        "results/CIFAR10_BigGAN_v1/train_cifar10_20200410-13_44_27_398/textlog/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in first block"
        marker: "."
    BigGAN_CBN_in_blocks_2:
      log_file:
        "results/CIFAR10_BigGAN_v1/train_cifar10_20200527-17_01_36_617/textlog/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in last block"
        marker: "."
  saved_file: "cbn_location.pdf"

save_FID_cbn_index_012_figure:
  xlabel: "Epoch"
  ylabel: "FID"
  fontsize:
    tick_fs: 14
    xylabel_fs: 20
    legend_size: 12
  properties:
    xlim:
      - 0
      - 336
    ylim:
      - 0
      - 30
  get_min_value: true
  add_auxi_label: false
  lines:
    cbn_index_0:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CBN_position_\
      20200908-11_23_31_588"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in block 0"
        marker: "."
    cbn_index_1:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CBN_position_\
      20200908-17_39_57_212"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in block 1"
        marker: "."
    cbn_index_2:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CBN_position_\
          20200908-11_25_10_095"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in block 2"
        marker: "."
    cbn_index_01:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CBN_position_\
          20200908-17_49_19_524"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in block 0,1"
        marker: "."
    cbn_index_02:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CBN_position_\
          20200908-19_07_18_012"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in block 0,2"
        marker: "."
    cbn_index_12:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CBN_position_\
          20200908-19_12_19_401"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in block 1,2"
        marker: "."
    cbn_index_012:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CBN_position_\
          20200908-11_21_03_339"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CBN in block 0,1,2"
        marker: "."
  saved_file: "cbn_index012.pdf"


train_cifar10_CMConv_position:
  base:
    - train_cifar10_CBN_position
  args:
    model: "exp.cmconv.net_biggan_cmconv"
    batch_size: 32
#    batch_size: 16
    G_param: ""
  generator:
    overwrite: true
    CMConv_index:
      - 0
#      - 1
#      - 2
    CMConv_cfg:
      name: "EmbeddingModulatedConv2d"
      n_classes: 10
      zero_embedding: true
      ModulatedConv2d_cfg:
        name: "ModulatedConv2d"
        kernel_size: 3
        use_affine: false
#        use_affine: true
        demodulate: true
#        demodulate: false
        init: "ortho"
        style_plus_one: true
  GAN_metric:
    num_inception_images: 50000
#    num_inception_images: 500


save_FID_CMConv_CBN_location_figure:
  args:
    num_gpus: 1
  start:
    name: "save_FID_CMConv_CBN_location_figure"
  properties:
    xlim:
      - 0
      - 500
    ylim:
      - 0
      - 50
  fid_files:
    BigGAN_CBN_in_all_blocks:
      log_file:
        "results/CIFAR10_BigGAN_v1/train_cifar10_20200809-11_52_04_071/textlog/evaltf.ma0.FID_tf.log"
      properties:
#        label: "[FID=7.26]   CBN in all blocks"
        label: "CBN in all blocks"
        c: 'r'
#        marker: "*"
    BigGAN_CBN_in_blocks_0:
      log_file:
        "results/CIFAR10_BigGAN_v1/train_cifar10_20200809-11_56_18_932/textlog/evaltf.ma0.FID_tf.log"
      properties:
#        label: "[FID=6.72]   CBN in first block"
        label: "CBN in first block"
        c: 'g'
#        marker: "h"
    BigGAN_CBN_in_blocks_2:
      log_file:
        "results/CIFAR10_BigGAN_v1/train_cifar10_20200809-11_59_30_697/textlog/evaltf.ma0.FID_tf.log"
      properties:
#        label: "[FID=9.05]   CBN in last block"
        label: "CBN in last block"
        c: 'b'
#        marker: "d"
    CMConv_all_blocks:
      log_file:
        "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_vs_CBN_20200809-16_16_34_916/textlog/evaltf.ma0.FID_tf.log"
      properties:
#        label: "[FID=22.58] CMConv in all block"
        label: "CMConv in all block"
#        marker: "*"
        c: 'r'
        ls: "--"
    CMConv_first_blocks:
      log_file:
        "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_vs_CBN_20200809-16_19_42_944/textlog/evaltf.ma0.FID_tf.log"
      properties:
#        label: "[FID=6.87]   CMConv in first block"
        label: "CMConv in first block"
#        marker: "h"
        c: 'g'
        ls: "--"
    CMConv_last_blocks:
      log_file:
        "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_vs_CBN_20200809-16_21_12_570/textlog/evaltf.ma0.FID_tf.log"
      properties:
#        label: "[FID=17.20] CMConv in last block"
        label: "CMConv in last block"
        #        marker: "h"
        c: 'b'
        ls: "--"
  saved_file: "cmconv_cbn_location.pdf"

save_FID_CMConv_index_012_figure:
  xlabel: "Epoch"
  ylabel: "FID"
  fontsize:
    tick_fs: 14
    xylabel_fs: 20
    legend_size: 12
  properties:
    xlim:
      - 0
      - 336
    ylim:
      - 0
      - 30
  get_min_value: true
#  add_auxi_label: true
  add_auxi_label: false
  lines:
    cmc_index_0:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_position_\
      20200909-18_32_59_459"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CMConv in block 0"
        marker: "."
    cmc_index_1:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_position_\
          20200909-22_53_58_204"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CMConv in block 1"
        marker: "."
    cmc_index_2:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_position_\
          20200909-22_56_35_345"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CMConv in block 2"
        marker: "."
    cmc_index_01:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_position_\
          20200909-23_01_38_960"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CMConv in block 0,1"
        marker: "."
    cmc_index_02:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_position_\
          20200909-23_03_09_766"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CMConv in block 0,2"
        marker: "."
    cmc_index_12:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_position_\
          20200909-23_18_34_635"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CMConv in block 1,2"
        marker: "."
    cmc_index_012:
      result_dir: "results/CIFAR10_BigGAN_v1/train_cifar10_CMConv_position_\
          20200909-22_58_58_446"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "CMConv in block 0,1,2"
        marker: "."
  saved_file: "cmconv_index012.pdf"


train_cifar10_CMConv_disc:
  base:
    - train_cifar10_CBN_position
  args:
    model: "exp.cmconv.net_cmconv_discriminator"
    batch_size: 32
#    batch_size: 16
    G_param: ""
  generator:
    overwrite: true
    CMConv_index:
      - 0
#      - 1
#      - 2
    CMConv_cfg:
      name: "EmbeddingModulatedConv2d"
      n_classes: 10
      zero_embedding: true
      ModulatedConv2d_cfg:
        name: "ModulatedConv2d"
        kernel_size: 3
        use_affine: false
#        use_affine: true
        demodulate: true
#        demodulate: false
        init: "ortho"
        style_plus_one: true
  discriminator:
    CMConv_cfg:
      name: "EmbeddingModulatedConv2d"
      n_classes: 10
      zero_embedding: true
      ModulatedConv2d_cfg:
        name: "ModulatedConv2d"
        kernel_size: 3
        use_affine: false
#        use_affine: true
        demodulate: true
#        demodulate: false
        init: "ortho"
        style_plus_one: true
  GAN_metric:
    num_inception_images: 50000
#    num_inception_images: 500


train_cifar10_CMConv_full_conv_disc:
  base:
    - train_cifar10_CBN_position
  args:
    model: "exp.cmconv.net_cmconv_full_conv_discriminator"
    batch_size: 32
#    batch_size: 16
    G_param: ""
    dataset_kwargs:
      train: false
  discriminator:
    cmconv_out_channel: 1
    CMConv_cfg:
      name: "EmbeddingModulatedConv2d"
      n_classes: 10
      zero_embedding: false
      spectral_norm: true
      ModulatedConv2d_cfg:
        name: "ModulatedConv2d"
        kernel_size: 3
        use_affine: false
#        use_affine: true
        demodulate: true
#        demodulate: false
        init: "ortho"
        style_plus_one: true
  GAN_metric:
    num_inception_images: 50000
#    num_inception_images: 500