train_cifar10:
  args:
    shuffle: true
#    batch_size: 50
    batch_size: 32
    dataset: C10
    use_data_root: true
    data_root: "datasets/cifar10"
    num_workers: 0
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_epochs: 500
    num_D_steps: 4
    G_ch: 64
    D_ch: 64
    G_lr: 2.e-4
    D_lr: 2.e-4
    G_ortho: 0.0
    G_attn: '0'
    D_attn: '0'
    G_init: N02
    D_init: N02
    ema: true
    use_ema: true
    ema_start: 1000
    test_every: 5000000
#    test_every: 500
    save_every: 2000
    num_best_copies: 1
    num_save_copies: 1
    seed: 0
    model: "exp.biggan.BigGAN"
    G_eval_mode: true
  train_dataloader:
    dataset_kwargs:
      val_split: 0.04
      train: validate
  val_dataloader:
    dataset_kwargs:
      train: false
    use_training_sampler: true
  test_every_images: 500000
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: "datasets/tf_fid_stat/\
      fid_stats_tf_cifar10_train_32.npz"
    tf_inception_model_dir: "datasets/tf_inception_model"
#    num_inception_images: 500
    num_inception_images: 50000
  Discriminator:
    weight_decay: 0.


train_2k_weight_decay_0:
  base:
    - train_cifar10
  args:
    D_ch: 32
    use_ema: false
    num_epochs: 50000000
  train_dataloader:
    dataset_kwargs:
      val_split: 0.04
      train: validate
  test_every_images: 20000
  GAN_metric:
    num_inception_images: 5000
  Discriminator:
    weight_decay: 0.

train_2k_weight_decay:
  base:
    - train_2k_weight_decay_0
  Discriminator:
    weight_decay: 0.1
#    weight_decay: 0.01
#    weight_decay: 0.001
#    weight_decay: 0.0001

train_2k_weight_decay_unified_GAN:
  base:
    - train_2k_weight_decay_0
  args:
    model: "exp.unified_loss.BigGAN_unified_loss"
    which_train_fn: "exp.unified_loss.train_fns"
  Discriminator:
#    weight_decay: 0.1
#    weight_decay: 0.01
#    weight_decay: 0.001
    weight_decay: 0.0001
  unified_loss:
#    gamma: 5.
    gamma: 1.
    margin: 0.
    default_label: 0
#    default_label: -1


