make_hdf5_ImageNet32:
  args:
    dataset: I32
    num_workers: 16
#    num_workers: 8
    batch_size: 256
    data_root: "datasets/ILSVRC/Data/CLS-LOC/train"
  index_filename: 'datasets/BigGAN-PyTorch-1-exp/ILSVRC_{}_index.npz'
  saved_hdf5: "datasets/BigGAN-PyTorch-1-exp/ILSVRC_{}.hdf5"

calculate_inception_moments_ImageNet32:
  args:
    dataset: I32_hdf5
    data_root: "datasets/BigGAN-PyTorch-1-exp/ILSVRC_I32.hdf5"
    num_workers: 16
    batch_size: 2048
  saved_inception_moments: "datasets/BigGAN-PyTorch-1-exp/\
  ILSVRC_{}_inception_moments.npz"

make_hdf5_ImageNet64:
  args:
    dataset: I64
#    num_workers: 16
    num_workers: 8
    batch_size: 256
    data_root: "datasets/ILSVRC/Data/CLS-LOC/train"
  index_filename: 'datasets/BigGAN-PyTorch-1-exp/ILSVRC_{}_index.npz'
  saved_hdf5: "datasets/BigGAN-PyTorch-1-exp/ILSVRC_{}.hdf5"

calculate_inception_moments_ImageNet64:
  args:
    dataset: I64_hdf5
    data_root: "datasets/BigGAN-PyTorch-1-exp/ILSVRC_I64.hdf5"
    num_workers: 16
    batch_size: 2048
  saved_inception_moments: "datasets/BigGAN-PyTorch-1-exp/\
  ILSVRC_{}_inception_moments.npz"


make_hdf5_ImageNet128:
  args:
    dataset: I128
    num_workers: 16
#    num_workers: 8
    batch_size: 256
    data_root: "datasets/ILSVRC/Data/CLS-LOC/train"
  index_filename: 'datasets/BigGAN-PyTorch-1-exp/ILSVRC_{}_index.npz'
  saved_hdf5: "datasets/BigGAN-PyTorch-1-exp/ILSVRC_{}.hdf5"

calculate_inception_moments_ImageNet128:
  args:
    dataset: I128_hdf5
    data_root: "datasets/BigGAN-PyTorch-1-exp/ILSVRC_I128.hdf5"
    num_workers: 16
    batch_size: 2048
  saved_inception_moments: "datasets/BigGAN-PyTorch-1-exp/\
  ILSVRC_{}_inception_moments.npz"


