calculate_inception_moments:
  args:
    num_workers: 8
    batch_size: 64
    shuffle: false
  saved_inception_moments: "datasets/torch_fid_stat/\
  mnist_svhn_inception_moments.npz"
  dataset:
    resolution: 32
    n_classes: 20
    mnist_root: datasets/mnist
    svhn_root: datasets/svhn

train_unified_GAN:
  args:
    shuffle: true
    batch_size: 64
    dataset: mnist_svhn
    num_workers: 0
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_epochs: 1000
    num_D_steps: 4
#    G_ch: 32
#    D_ch: 32
    G_ch: 16
    D_ch: 16
    G_lr: 0.0002
    D_lr: 0.0002
    G_ortho: 0.0
    G_attn: '0'
    D_attn: '0'
    G_init: N02
    D_init: N02
#    G_init: "ortho"
#    D_init: "ortho"
    ema: true
    use_ema: true
    ema_start: 5000
    test_every: -1
    save_every: 2000
    num_best_copies: 1
    num_save_copies: 1
    seed: 0
    model: exp.unified_loss.BigGAN_unified_loss
#    G_eval_mode: true
    which_train_fn: exp.mixed_mnist_svhn.train_fns
    sv_log_interval: -1
  dataset:
    resolution: 32
    n_classes: 20
    mnist_root: datasets/mnist
    svhn_root: datasets/svhn

  test_every_images: 133257
  use_unofficial_FID: true
  inception_file: "datasets/torch_fid_stat/\
  mnist_svhn_inception_moments.npz"
  Discriminator:
    output_dim: 14
    weight_decay: 0.01
  Generator:
    weight_decay: 0.001
  unified_loss:
#    mode: "only_p"
    mode: "p_and_n"
    gamma: 1.0
    margin: 0.0
  optim_type: 'adam'

debug_train_unified_GAN:
  base: train_unified_GAN
  args:
    num_inception_images: 500
