train_unified_GAN:
  args:
    shuffle: true
    batch_size: 32
    dataset: C100
    use_data_root: true
    data_root: datasets/cifar100
    num_workers: 0
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_epochs: 1000
    num_D_steps: 4
    G_ch: 64
    D_ch: 64
    G_lr: 0.0002
    D_lr: 0.0002
    G_ortho: 0.0
    G_attn: '0'
    D_attn: '0'
    G_init: N02
    D_init: N02
#    G_init: "ortho"
#    D_init: "ortho"
    ema: true
    use_ema: true
    ema_start: 5000
    test_every: -1
    save_every: 2000
    num_best_copies: 1
    num_save_copies: 1
    seed: 0
    model: exp.unified_loss.BigGAN_unified_loss
#    G_eval_mode: true
    which_train_fn: exp.unified_loss.train_fns
    sv_log_interval: -1
  train_dataloader:
    dataset_kwargs:
      train: true
  val_dataloader:
    dataset_kwargs:
      train: false
    use_training_sampler: true
  test_every_images: 500000
#  test_every_images: 50000
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: datasets/tf_fid_stat/fid_stats_tf_cifar100_train_32.npz
    tf_inception_model_dir: datasets/tf_inception_model
    num_inception_images: 50000
#    num_inception_images: 500
  Discriminator:
    weight_decay: 0.0005
  Generator:
#    weight_decay: 0.0
    weight_decay: 0.0005
  unified_loss:
#    mode: "only_p"
    mode: "p_and_n"
    gamma: 1.0
    margin: 0.0
  optim_type: 'adam'


debug_train_unified_GAN:
  base: train_unified_GAN
  GAN_metric:
    num_inception_images: 500
  test_every_images: 50000


eval_trained_model:
  base: train_unified_GAN
  eval_cfg:
    eval: true
#    path: "~/nni-experiments/EZrNsffk/trials/B5eOM/\
#    B5eOM/code/results/Unified_GAN_CIFAR100/train_unified_GAN-\
#    20201024_1627_358/biggan/weights/exp/G_ema_best0.pth"

    path: "~/nni-experiments/GViHqCbe/trials/lGz2H/\
    lGz2H/code/results/Unified_GAN_CIFAR100/train_unified_GAN/biggan/weights/exp/\
    G_ema_best_FID0.pth"
#    path: "~/nni-experiments/GViHqCbe/trials/lGz2H/\
#        lGz2H/code/results/Unified_GAN_CIFAR100/train_unified_GAN/biggan/weights/exp/\
#        G_ema_best_IS0.pth"

#    path: "~/nni-experiments/GViHqCbe/trials/aJ4nR/\
#    aJ4nR/code/results/Unified_GAN_CIFAR100/train_unified_GAN/biggan/weights/exp/\
#    G_ema_best_FID0.pth"
#    path: "~/nni-experiments/GViHqCbe/trials/aJ4nR/\
#    aJ4nR/code/results/Unified_GAN_CIFAR100/train_unified_GAN/biggan/weights/exp/\
#    G_ema_best_IS0.pth"




