train_cifar10:
  args:
    shuffle: true
#    batch_size: 50
    batch_size: 32
    dataset: C10
    use_data_root: true
    data_root: "datasets/cifar10"
    num_workers: 0
    num_G_accumulations: 1
    num_D_accumulations: 1
    num_epochs: 500
    num_D_steps: 4
    G_ch: 64
    D_ch: 64
    G_lr: 2.e-4
    D_lr: 2.e-4
    G_ortho: 0.0
    G_attn: '0'
    D_attn: '0'
    G_init: N02
    D_init: N02
    ema: true
    use_ema: true
#    ema_start: 1000
    ema_start: 5000
    test_every: 5000000
    save_every: 2000
    num_best_copies: 1
    num_save_copies: 1
    seed: 0
    model: "exp.unified_loss.BigGAN_unified_loss"
    which_train_fn: "exp.unified_loss.train_fns"
  val_dataloader:
    dataset_kwargs:
      train: false
    use_training_sampler: true
  test_every_epoch: 10
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: "datasets/tf_fid_stat/\
      fid_stats_tf_cifar10_train_32.npz"
    tf_inception_model_dir: "datasets/tf_inception_model"
#    num_inception_images: 500
    num_inception_images: 50000
  Discriminator:
#    weight_decay: 0.0005
    weight_decay: 0.0001
  unified_loss:
#    gamma: 5.
    gamma: 1.
    margin: 0.
    default_label: 0
#    default_label: -1


save_FID_cifar10:
  xlabel: "Epoch"
  ylabel: "FID"
  fontsize:
    tick_fs: 14
    xylabel_fs: 20
    legend_size: 12
  properties:
    xlim:
      - 0
      - 500
    ylim:
      - 0
      - 30
  get_min_value: true
#  add_auxi_label: true
  lines:
    biggan:
      result_dir: "results/CIFAR10/train_cifar10_\
      20201002-17_42_27_041"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "BigGAN [FID=7.05]"
        marker: ""
    Unified-GAN:
      result_dir: "results/UnifiedLoss/train_cifar10_\
      20201003-19_59_28_513"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "Unified-GAN [FID=6.83]"
        marker: ""
  saved_file: "fid_cifar10.pdf"

save_IS_cifar10:
  xlabel: "Epoch"
  ylabel: "IS"
  fontsize:
    tick_fs: 14
    xylabel_fs: 20
    legend_size: 12
  properties:
    xlim:
      - 0
      - 500
#    ylim:
#      - 0
#      - 50
  get_min_value: false
#  add_auxi_label: true
  lines:
    biggan:
      result_dir: "results/CIFAR10/train_cifar10_\
      20201002-17_42_27_041"
      sub_path: "textdir/evaltf.ma1.IS_mean_tf.log"
      properties:
        label: "BigGAN [IS=9.14]"
        marker: ""
    Unified-GAN:
      result_dir: "results/UnifiedLoss/train_cifar10_\
      20201003-19_59_28_513"
      sub_path: "textdir/evaltf.ma1.IS_mean_tf.log"
      properties:
        label: "Unified-GAN [IS=9.37]"
        marker: ""
  saved_file: "IS_cifar10.pdf"


save_D_loss_and_FID_cifar10:
  logits_file:
    real: textdir/train.D_loss.D_real_loss.log
    generated: textdir/train.D_loss.G_loss.log
    validation: textdir/train.D_loss.D_val_loss.log
  colors:
    - green
    - blue_violet
    - black
  sample_interval: 100
#  sample_interval: 5
#  max_iter: 30000
  fid_file: textdir/evaltf.ma0.FID_tf.log
  fid_color: red
  suffix: 'pdf'
#  suffix: 'png'
  fontsize:
    xy_label: 20
  ylim:
    - -50
    - 350
  ax1_xlabel: "ULoss(x)"
  exps:
    unified_gan_cifar10:
      results_dir: "results/UnifiedLoss/train_cifar10_\
      20201003-19_59_28_513"
      iter_per_epoch: 390
      anno_offset:
        - -9000
        - -10



train_cifar100:
  base:
    - train_cifar10
  args:
    dataset: C100
    data_root: "datasets/cifar100"
  GAN_metric:
    name: TFFIDISScore
    tf_fid_stat: "datasets/tf_fid_stat/\
      fid_stats_tf_cifar100_train_32.npz"
    tf_inception_model_dir: "datasets/tf_inception_model"
#    num_inception_images: 500
    num_inception_images: 50000
  Discriminator:
    weight_decay: 0.0005
  unified_loss:
#    gamma: 5.
    gamma: 1.
    margin: 0.
    default_label: 0
#    default_label: -1


save_FID_cifar100:
  xlabel: "Epoch"
  ylabel: "FID"
  fontsize:
    tick_fs: 14
    xylabel_fs: 20
    legend_size: 12
  properties:
    xlim:
      - 0
      - 500
    ylim:
      - 0
      - 30
  get_min_value: true
#  add_auxi_label: true
  lines:
    biggan:
      result_dir: "results/CIFAR10/train_cifar100_\
      20201002-19_37_05_825"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "BigGAN [FID=10.18]"
        marker: "."
    Unified-GAN:
      result_dir: "results/UnifiedLoss/train_cifar100_\
      20201003-20_59_01_333"
      sub_path: "textdir/evaltf.ma0.FID_tf.log"
      properties:
        label: "Unified-GAN [FID=8.60]"
        marker: "."
  saved_file: "fid_cifar100.pdf"


save_IS_cifar100:
  xlabel: "Epoch"
  ylabel: "IS"
  fontsize:
    tick_fs: 14
    xylabel_fs: 20
    legend_size: 12
  properties:
    xlim:
      - 0
      - 500
#    ylim:
#      - 0
#      - 50
  get_min_value: false
#  add_auxi_label: true
  lines:
    biggan:
      result_dir: "results/CIFAR10/train_cifar100_\
      20201002-19_37_05_825"
      sub_path: "textdir/evaltf.ma1.IS_mean_tf.log"
      properties:
        label: "BigGAN [IS=10.89]"
        marker: ""
    Unified-GAN:
      result_dir: "results/UnifiedLoss/train_cifar100_\
      20201003-20_59_01_333"
      sub_path: "textdir/evaltf.ma1.IS_mean_tf.log"
      properties:
        label: "Unified-GAN [IS=12.34]"
        marker: ""
  saved_file: "IS_cifar10.pdf"

